/**
 * =============================================
 * DATOS MOCK — Contenido de prueba del feed
 * Reemplazar con API real en producción
 * =============================================
 */

const STORIES_DATA = [
  {
    id: 'own',
    username: 'Tu historia',
    avatar: 'https://i.pravatar.cc/150?img=12',
    isOwn: true,
    seen: false,
  },
  {
    id: 's1',
    username: 'maria_garcia',
    avatar: 'https://i.pravatar.cc/150?img=1',
    seen: false,
  },
  {
    id: 's2',
    username: 'carlos_photo',
    avatar: 'https://i.pravatar.cc/150?img=3',
    seen: false,
  },
  {
    id: 's3',
    username: 'luna_travel',
    avatar: 'https://i.pravatar.cc/150?img=5',
    seen: true,
  },
  {
    id: 's4',
    username: 'foodie_es',
    avatar: 'https://i.pravatar.cc/150?img=9',
    seen: false,
  },
  {
    id: 's5',
    username: 'fitness_pro',
    avatar: 'https://i.pravatar.cc/150?img=11',
    seen: true,
  },
  {
    id: 's6',
    username: 'art_studio',
    avatar: 'https://i.pravatar.cc/150?img=15',
    seen: false,
  },
  {
    id: 's7',
    username: 'tech_daily',
    avatar: 'https://i.pravatar.cc/150?img=20',
    seen: false,
  },
];

const POSTS_DATA = [
  {
    id: 'p1',
    username: 'maria_garcia',
    avatar: 'https://i.pravatar.cc/150?img=1',
    location: 'Barcelona, España',
    image: 'https://picsum.photos/seed/insta1/1080/1080',
    likes: 1247,
    liked: false,
    saved: false,
    caption: 'Atardecer mágico en la playa 🌅 No hay nada como estos momentos.',
    commentsCount: 89,
    timestamp: 'Hace 2 horas',
    carousel: false,
  },
  {
    id: 'p2',
    username: 'carlos_photo',
    avatar: 'https://i.pravatar.cc/150?img=3',
    location: 'Montaña Sagrada',
    image: 'https://picsum.photos/seed/insta2/1080/1080',
    likes: 3891,
    liked: true,
    saved: true,
    caption: 'La naturaleza siempre encuentra la manera de sorprendernos. 📸',
    commentsCount: 234,
    timestamp: 'Hace 5 horas',
    carousel: true,
    carouselCount: 3,
  },
  {
    id: 'p3',
    username: 'luna_travel',
    avatar: 'https://i.pravatar.cc/150?img=5',
    location: 'Tokio, Japón',
    image: 'https://picsum.photos/seed/insta3/1080/1080',
    likes: 5623,
    liked: false,
    saved: false,
    caption: 'Explorando las calles de Shibuya. Cada rincón es una foto 📷✨',
    commentsCount: 412,
    timestamp: 'Hace 8 horas',
    carousel: false,
  },
  {
    id: 'p4',
    username: 'foodie_es',
    avatar: 'https://i.pravatar.cc/150?img=9',
    location: null,
    image: 'https://picsum.photos/seed/insta4/1080/1080',
    likes: 892,
    liked: false,
    saved: false,
    caption: 'Brunch del domingo hecho en casa 🥑🍳 Receta en stories!',
    commentsCount: 56,
    timestamp: 'Hace 12 horas',
    carousel: false,
  },
  {
    id: 'p5',
    username: 'art_studio',
    avatar: 'https://i.pravatar.cc/150?img=15',
    location: 'Estudio Creativo',
    image: 'https://picsum.photos/seed/insta5/1080/1080',
    likes: 2104,
    liked: false,
    saved: true,
    caption: 'Nueva pieza terminada después de semanas de trabajo. ¿Qué opináis?',
    commentsCount: 178,
    timestamp: 'Hace 1 día',
    carousel: false,
  },
];
